- name: Initialize doryd default parameters
  set_fact:
    result: {}
    doryd_exists: false
   
- name: Check whether doryd as a container exists for multimaster Kubernetes/Openshift setup
  shell: kubectl get pods --namespace kube-system -o wide | grep doryd
  register: result
  failed_when: false
  changed_when: false
  when: hostvars.localhost.doryd_as_container == true
 
- name: Set flag doryd_exists as true if already running
  set_fact:
    doryd_exists: true
  when: result is defined and result.rc == 0 
 
- name: Deployment on Openshift cluster when version is 3.11
  shell: |
    oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:doryd
    cd {{playbook_dir}}
    cd ..
    oc create -f provisioner/OpenShift/dep-kube-storage-controller-ocp311.yaml
  become: yes
  when: hostvars.localhost.openshift_setup == true and hostvars.localhost.doryd_as_container == true and doryd_exists == false

- name: Deployment on Kubernetes cluster when version is 1.13 and beyond
  shell: |
    cd {{playbook_dir}}
    cd .. 
    kubectl create -f provisioner/k8s/dep-kube-storage-controller-k8s113.yaml
  become: yes
  when: hostvars.localhost.k8s_setup == true and hostvars.localhost.doryd_as_container == true and doryd_exists == false 
  
- name: create doryd service
  copy:
    src: ../files/doryd.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  when: hostvars.localhost.doryd_as_service == true

- name: restart doryd service, also issue daemon-reload to pick up config changes
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: doryd.service
  when: hostvars.localhost.doryd_as_service == true 


